@divine_the_number_HostAddress = http://localhost:5271

GET {{divine_the_number_HostAddress}}/todos/
Accept: application/json

###

GET {{divine_the_number_HostAddress}}/todos/1
Accept: application/json

###
